name: MCNSAChat
main: com.mcnsa.mcnsachat3.plugin.MCNSAChat3
version: 3.0.0.3-SNAPSHOT
authors: [maboughey, mcnsa, mcnsa.com]
depend: [PermissionsEx]

commands:
  chelp:
    description: derp
  c:
    description: derp
  cmute:
    description: derp
  clist:
    description: derp
  clisten:
    description: derp
  csearch:
    description: derp
  list:
    description: derp
  me:
    description: derp
  msg:
    description: derp
  r:
    description: derp
  clock:
    description: derp
  cmove:
    description: derp
  creconnect:
    description: derp
  creload:
    description: derp
  cto:
    description: derp
  calias:
    description: derp
  ccolor:
    description: derp
  cmode:
    description: derp
  cname:
    description: derp
  dicks:
    description: derp
  pong:
    description: derp
  rand:
    description: derp
  ranks:
    description: derp
  mab:
    description: derp